# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouter_version.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from dbConnection import db_connection
import functions as my_fnc


class Ui_Version(object):
    nom_version_txt=""
    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(399, 209)
        Form.setFixedSize(399,209)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 70, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.nom_version = QtWidgets.QLineEdit(Form)
        self.nom_version.setGeometry(QtCore.QRect(150, 70, 151, 20))
        self.nom_version.setObjectName("nom_version")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btn_add.setStyleSheet("QPushButton:hover:!pressed\n"
                                      "{\n"
                                      "  border: 1px solid lime;\n"
                                      "background-color: rgb(0, 0, 0);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton\n"
                                      "{\n"
                                      "background-color: rgb(0, 0, 0);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "padding:2px;\n"
                                      "}")
        self.btn_add.setIcon(QIcon('add.png'))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ajouter Version"))
        Form.setWindowIcon(QIcon('iconBig.gif'))
        self.label.setText(_translate("Form", "Nom Version"))
        self.btn_add.setText(_translate("Form", "Ajouter"))

        """ my logic goes here """
        self.btn_add.clicked.connect(self.add_version)

    def add_version(self):
        sqliteConnection, cursor = db_connection()
        nom_version_txt = self.nom_version.text()

        if nom_version_txt != "":

            try:
                add_query = """ INSERT INTO Version(name_version) VALUES(?);"""
                name_to_add = (nom_version_txt,)
                cursor.execute(add_query,name_to_add)
                sqliteConnection.commit()
                print("name added successfully ")
                self.nom_version.clear()

            except sqlite3.Error as error:

                if str(error)[:6]=="UNIQUE":
                    my_fnc.show_popup(self,'version_exist')
                    print('Version already exists')



        else:
            print('please enter version name')
            my_fnc.show_popup(self,'version_name')
        #show popup here



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Version()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
